# Cycling protocol configuration
dataset_name: cycling

input_excel: /Processed_Charge_All_Cycles.xlsx
output_csv: battery_changepoints_cycling_penalty10.csv

changepoint:
  model: rbf
  penalty: 10
  jump: 1

soh:
  method: cycle2

postprocessing:
  clustering: true

visualization:
  save_example: true

