# OCV-SOC configuration
dataset_name: ocv

input_excel: /battery_data_summary_OCV.xlsx
output_csv: battery_changepoints_ocv_penalty50.csv

changepoint:
  model: rbf
  penalty: 50
  jump: 5

soh:
  method: nominal
  nominal_capacity: 1.85

postprocessing:
  clustering: false

visualization:
  save_example: true
